version: 2.1
executors:
    node8:
        docker:
            - image: mcr.microsoft.com/playwright:bionic
        environment:
            NODE_ENV: development
            NPM_CONFIG_PREFIX: ~/.npm-global
commands:
    setup:
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
            - run:
                  name: Installing Dependencies
                  command: npm i
            - save_cache:
                  paths:
                      - node_modules
                  key: v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
jobs:
    build_and_test:
        executor: node8

        steps:
            - setup
            - run:
                  name: Run tests
                  command: npm run test

workflows:
    version: 2
    build:
        jobs:
            - build_and_test
